name: Deploy
on:
  push:
    branches:
      - master
env:
  GITHUB_SHA: ${{ secrets.GITHUB_SHA }}
jobs:
  deployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        name: Install node
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: |
          yarn build
          echo $GITHUB_SHA > ./build/version
        env:
          REACT_APP_API_PATH: ${{ secrets.REACT_APP_API_PATH }}
      - name: Deploy app
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/artyom-88/artyom-88.github.io.git
          yarn gh-pages -d build -u "Artem Ganev <a.a.ganev@gmail.com>" -m ${GITHUB_SHA}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_SHA: ${{ secrets.GITHUB_SHA }}
