name: Node CI
on:
  pull_request:
    branches:
      - develop
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: Install node
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run audit
        run: yarn audit:ci --high
      - name: Run tests
        run: yarn testCI
      - name: Build app
        run: yarn build
