name: Playwright Tests
on:
  pull_request:
    branches:
      - develop
      - master
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.48.1-noble
    env:
      HOME: /root
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
    steps:
    - uses: actions/checkout@v4
    - name: Ping API
      run: curl "${{ env.VITE_API_URL }}/api/health"
    - uses: pnpm/action-setup@v4
      name: Install PNPM
      with:
        run_install: false
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - uses: actions/cache@v4
      name: Setup cache
      with:
        path: |
          ${{ env.STORE_PATH }}
          ./node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Run Playwright tests
      run: pnpm exec playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 10
